version: '3.6'
services:
  datalake:
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./normalized_datalake
      args:
      - IRIS_PROJECT_FOLDER_NAME=datalake-atelier-project
    image: amirsamary/irisdemo:mobilebanking_datalake
    command: --key /shared/iris.key
    hostname: datalake
    ports:
    # 51773 is the superserver default port
    - "9095:51773"
    # 52773 is the webserver/management portal port
    - "9094:52773"
    volumes:
    - ${PWD}/normalized_datalake/shared/:/shared
    networks:
    - bankingtrnsrv-tier
    - datalake-tier

  bankingcore:
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./banking_core
      args:
      - IRIS_PROJECT_FOLDER_NAME=bankingcore-atelier-project
    image: amirsamary/irisdemo:mobilebanking_bankingcore
    command: --key /shared/iris.key
    hostname: bankingcore
    ports:
    # 51773 is the superserver default port
    - "9091:51773"
    # 52773 is the webserver/management portal port
    - "9090:52773"
    volumes:
    - ${PWD}/banking_core/shared/:/shared
    networks:
    - bankingcore-tier

  bankingtrnsrv:
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./banking_trn_srv
      args:
      - IRIS_PROJECT_FOLDER_NAME=bankingtrnsrv-atelier-project
    image: amirsamary/irisdemo:mobilebanking_bankingtrnsrv
    command: --key /shared/iris.key
    hostname: bankingtrnsrv
    ports:
    # 51773 is the superserver default port
    - "9093:51773"
    # 52773 is the webserver/management portal port
    - "9092:52773"
    volumes:
    - ${PWD}/banking_trn_srv/shared/:/shared
    networks:
    - bankingtrnsrv-tier
    - bankingcore-tier

  advancedanalytics:
    build: ./advanced_analytics
    image: amirsamary/irisdemo:mobilebanking_advancedanalytics
    ports:
    - "9096:9090"   # Zeppelin
    - "9097:8080"   # Spark Master Portal
    - "9098:8081"   # Spark Worker Portal
    volumes:
    - $PWD/advanced_analytics/shared/:/shared
    environment:
    - IRIS_MASTER_HOST=datalake # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APP 
    networks:
    - datalake-tier

networks:
  bankingtrnsrv-tier:
    driver: bridge
  bankingcore-tier:
    driver: bridge
  datalake-tier:
    driver: bridge 
