version: '3.6'

services:
  datalake:
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./normalized_datalake
      args:
      - IRIS_PROJECT_FOLDER_NAME=datalake-atelier-project
    image: amirsamary/irisdemo:mobilebanking_datalake
    command: --key /irislicense/iris.key
    hostname: datalake
    ports:
    # 51773 is the superserver default port
    - "9095:51773"
    # 52773 is the webserver/management portal port
    - "9094:52773"
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
    - type: bind
      source: ./normalized_datalake/shared/
      target: /shared

    networks:
    - bankingtrnsrv-tier
    - datalake-tier

  bankingcore:
    depends_on: 
      - datalake
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./banking_core
      args:
      - IRIS_PROJECT_FOLDER_NAME=bankingcore-atelier-project
    image: amirsamary/irisdemo:mobilebanking_bankingcore
    command: --key /irislicense/iris.key
    hostname: bankingcore
    ports:
    # 51773 is the superserver default port
    - "9091:51773"
    # 52773 is the webserver/management portal port
    - "9090:52773"
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
    - type: bind
      source: ./banking_core/shared/
      target: /shared
      
    networks:
    - bankingcore-tier

  bankingtrnsrv:
    depends_on: 
      - bankingcore
    # environment:
    # - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./banking_trn_srv
      args:
      - IRIS_PROJECT_FOLDER_NAME=bankingtrnsrv-atelier-project
    image: amirsamary/irisdemo:mobilebanking_bankingtrnsrv
    command: --key /irislicense/iris.key
    hostname: bankingtrnsrv
    ports:
    # 51773 is the superserver default port
    - "9093:51773"
    # 52773 is the webserver/management portal port
    - "9092:52773"
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
    - type: bind                            # The production will be looking into this folder for new PMML files
      source: ./common_shared               # that will be sent by the advancedanalytics service.
      target: /common_shared
    - type: bind
      source: ./banking_trn_srv/shared/
      target: /shared
                                             
    networks:
    - bankingtrnsrv-tier
    - bankingcore-tier

  advancedanalytics:
    depends_on: 
      - sparkmaster
    build: ./advanced_analytics
    image: amirsamary/irisdemo:mobilebanking_advancedanalytics
    ports:
    - "9096:9090"   # Zeppelin
    - 4141:4040     # Zeppelin Spark UI
    volumes:
    - type: bind                            # The production will be looking into this folder for new PMML files
      source: ./common_shared               # that will be sent by the advancedanalytics service.
      target: /common_shared
    - type: bind
      source: ./advanced_analytics/shared/
      target: /shared

    environment:
    - IRIS_MASTER_HOST=datalake # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APP 
    networks:
    - datalake-tier

  sparkmaster:
    depends_on: 
      - bankingtrnsrv
    image: amirsamary/irisdemo:spark-iris
    hostname: sparkmaster # Must be always sparkmaster
    environment:
      SPARK_NODE_TYPE: Master
      SPARK_PUBLIC_DNS: localhost
      IRIS_MASTER_HOST: datalake # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080   # Spark Master Portal
    volumes:
    - type: bind                            # Shared between all spark nodes. Good place to place a file we are working with.
      source: ./common_shared               # that will be sent by the advancedanalytics service.
      target: /common_shared
    networks:
    - datalake-tier

  worker1:
    depends_on: 
      - sparkmaster
    image: amirsamary/irisdemo:spark-iris
    hostname: worker1
    environment:
      IRIS_MASTER_HOST: datalake # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081   # Spark Worker Portal
    volumes:
    - type: bind                            # Shared between all spark nodes. Good place to place a file we are working with.
      source: ./common_shared               # that will be sent by the advancedanalytics service.
      target: /common_shared

    networks:
    - datalake-tier

  worker2:
    depends_on: 
      - sparkmaster
    image: amirsamary/irisdemo:spark-iris
    hostname: worker2
    environment:
      IRIS_MASTER_HOST: datalake # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8082:8082   # Spark Worker Portal
    volumes:
    - type: bind                            # Shared between all spark nodes. Good place to place a file we are working with.
      source: ./common_shared               # that will be sent by the advancedanalytics service.
      target: /common_shared

    networks:
    - datalake-tier

  pos:
    build: ./pos
    image: amirsamary/irisdemo:mobilebanking_pos
    ports:
      - "9099:4200"
    #user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - OVERRID_BANKINGTRNSRV_HOST=
    command: "npm run proxy"
    networks:
      - bankingtrnsrv-tier
  
  # bankingui:
  #   build: ./bankingui
  #   image: amirsamary/irisdemo:mobilebanking_bankingui
  #   ports:
  #     - "9098:4200"
  #   command: "npm run proxy"
  #   networks:
  #     - bankingtrnsrv-tier

networks:
  bankingtrnsrv-tier:
    driver: bridge
  bankingcore-tier:
    driver: bridge
  datalake-tier:
    driver: bridge 
