version: '3.6'

volumes:
  common_shared:

services:

  readmissionrisksrv:
    depends_on:
      - RRLACESrv
    build:
      context: ./readmissionrisksrv
      args:
      - IRIS_PROJECT_FOLDER_NAME=readmissionrisksrv-atelier-project
    image: amirsamary/irisdemo:readmission_readmissionrisksrv
    command: --key /irislicense/iris.key
    hostname: readmissionrisksrv
    ports:
    - "9093:51773" # 51773 is the superserver default port
    - "9092:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
    - type: bind
      source: ./hl7files/
      target: /hl7files

  RRLACESrv:   # Readmission Risk LACE Service
    build:
      context: ./RRLACESrv
      args:
      - IRIS_PROJECT_FOLDER_NAME=RRLACESrv-atelier-project
    image: amirsamary/irisdemo:readmission_RRLACESrv
    command: --key /irislicense/iris.key
    hostname: RRLACESrv
    ports:
    - "9095:51773" # 51773 is the superserver default port
    - "9094:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
    - type: bind
      source: ./RRLACESrv_data/shared/
      target: /shared

  hisdb:
    depends_on:
      - RRLACESrv
    build:
      context: ./hisdb
      args:
      - IRIS_PROJECT_FOLDER_NAME=hisdb-atelier-project
    image: amirsamary/irisdemo:readmission_hisdb
    command: --key /irislicense/iris.key
    hostname: hisdb
    ports:
    - "9097:51773" # 51773 is the superserver default port
    - "9096:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense

  hisui:
    depends_on:
      - hisdb
    build:
      context: ./hisui
    image: amirsamary/irisdemo:readmission_hisui
    hostname: hisui
    ports:
    - "9098:4200" # Where Nodejs Will be listening
