version: '3.6'

volumes:
  common_shared:

services:

  readmissionrisksrv:
    build: 
      context: ./readmissionrisksrv
      args:
      - IRIS_PROJECT_FOLDER_NAME=readmissionrisksrv-atelier-project
    image: amirsamary/irisdemo:readmission_readmissionrisksrv
    command: --key /irislicense/iris.key
    hostname: readmissionrisksrv
    ports:
    - "9093:51773" # 51773 is the superserver default port
    - "9092:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense

  RRLACESrv:   # Readmission Risk LACE Service
    build: 
      context: ./RRLACESrv
      args:
      - IRIS_PROJECT_FOLDER_NAME=RRLACESrv-atelier-project
    image: amirsamary/irisdemo:readmission_RRLACESrv
    command: --key /irislicense/iris.key
    hostname: RRLACESrv
    ports:
    - "9095:51773" # 51773 is the superserver default port
    - "9094:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense
