version: '3.6'
services:
  datalake:
    environment:
    - ISC_DATA_DIRECTORY=/shared/iris
    build: 
      context: ./mydb
      args:
      - IRIS_PROJECT_FOLDER_NAME=mydb-atelier-project
    image: mydemo_datalake
    command: --key /shared/iris.key
    hostname: datalake
    ports:
    # 51773 is the superserver default port
    - "10001:51773"
    # 52773 is the webserver/management portal port
    - "10002:52773"
    volumes:
    - ${PWD}/mydb/shared/:/shared

  advancedanalytics:
    build: ./advanced_analytics
    image: mydemo_advancedanalytics
    ports:
    - "10003:9090"   # Zeppelin
    - "10004:8080"   # Spark Master Portal
    - "10005:8081"   # Spark Worker Portal
    volumes:
    - $PWD/advanced_analytics/shared/:/shared
    environment:
    - IRIS_MASTER_HOST=datalake # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APP 
