FROM amirsamary/irisdemo:tomcat
LABEL maintainer="Amir Samary <amir.samary@intersystems.com>"

# Example from:
# http://trimc-devops.blogspot.com/2015/03/running-docker-applications-apache.html
#ADD ./image_build_files/settings.xml /usr/local/tomcat/conf/
#ADD ./image_build_files/tomcat-users.xml /usr/local/tomcat/conf/

# This file should exist before you call docker-compose up.
#ADD ./image_build_files/myapp.wat /usr/local/tomcat/webaps

