# https://hub.docker.com/_/tomcat/
# https://docs.docker.com/samples/library/tomcat/
# http://trimc-devops.blogspot.com/2015/03/running-docker-applications-apache.html
# http://www.javathinking.com/2013/05/deploying-to-tomcat-7-with-maven.html

FROM tomcat:9.0
LABEL maintainer="Amir Samary <amir.samary@intersystems.com>"

