version: '2.4'

volumes:
  common_shared:

services:

  irisdb:
    build:
      context: ./irisdb
      args:
      - IRIS_PROJECT_FOLDER_NAME=setrainingirisdb-atelier-project
    image: amirsamary/irisdemo:setraining_irisdb
    command: --key /irislicense/iris.key
    hostname: irisdb
    ports:
    - "9093:51773" # 51773 is the superserver default port
    - "9092:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ../../IRISLicense/
      target: /irislicense

  advancedanalytics:
    depends_on: 
      irisdb:
        condition: service_healthy
    build: ./advanced_analytics
    image: amirsamary/irisdemo:mobilebanking_advancedanalytics
    cpu_percent: 25
    ports:
    - "10000:9090"     # Zeppelin
    - "10001:4040"     # Zeppelin Spark UI
    volumes:
    - common_shared:/common_shared   # The production will be looking into this folder for new PMML files
                                       # that will be sent by the advancedanalytics service.
    - type: bind
      source: ./advanced_analytics/shared/
      target: /shared

    environment:
    - IRIS_MASTER_HOST=irisdb # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APPINT

  sparkmaster:
    depends_on: 
    - advancedanalytics
    image: amirsamary/irisdemo:spark-iris
    hostname: sparkmaster # Must be always sparkmaster
    cpu_percent: 25
    environment:
      SPARK_NODE_TYPE: Master
      SPARK_PUBLIC_DNS: localhost
      IRIS_MASTER_HOST: irisdb
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080   # Spark Master Portal
    volumes:
    - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.

  worker1:
    depends_on: 
      - sparkmaster
    image: amirsamary/irisdemo:spark-iris
    hostname: worker1
    cpu_percent: 25
    environment:
      IRIS_MASTER_HOST: irisdb
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081   # Spark Worker Portal
    volumes:
    - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.  

  worker2:
    depends_on: 
      - sparkmaster
    image: amirsamary/irisdemo:spark-iris
    hostname: worker2
    cpu_percent: 25
    environment:
      IRIS_MASTER_HOST: irisdb
      IRIS_MASTER_PORT: 51773
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: sys
      IRIS_MASTER_NAMESPACE: APPINT

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8082:8082   # Spark Worker Portal
    volumes:
    - common_shared:/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
