FROM amirsamary/irisdemo:jboss
LABEL maintainer="Amir Samary <amir.samary@intersystems.com>"

# Uncomment when we have a war to add
ADD ./callcenterui-eclipse-project/target/callcenterui-1.0.0.war /opt/jboss/wildfly/standalone/deployments/app.war
