@ECHO OFF

# Constants:
CONTAINER_NAME=zeppelin
IRIS_MASTER_HOST=myapp
IRIS_MASTER_PORT=52773
IRIS_MASTER_USERNAME=SuperUser
IRIS_MASTER_PASSWORD=sys
IRIS_MASTER_NAMESPACE=APP

# The name of the image is based on the name of the folder
IMAGE_NAME=amirsamary/irisdemo:zeppelin-spark

docker run --rm -it -p 9090:9090 -p 9091:8080 -p 9092:8081 -v $PWD/shared:/shared -e IRIS_MASTER_HOST=$IRIS_MASTER_HOST -e IRIS_MASTER_PORT=$IRIS_MASTER_PORT -e IRIS_MASTER_USERNAME=$IRIS_MASTER_USERNAME -e IRIS_MASTER_PASSWORD=$IRIS_MASTER_PASSWORD -e IRIS_MASTER_NAMESPACE=$IRIS_MASTER_NAMESPACE --name $CONTAINER_NAME $IMAGE_NAME